<?php

return [
    'default_user' => 'ssh-user',
    'shell' => '/bin/bash',
    'prompt' => '$ ',
    'timeout' => 30,

    'apps' => [
        'ssh-shell' => [
            'file' => __DIR__ . '/apps/ssh-shell.php',
            'description' => 'Interactive SSH shell for FluxSSH',
            'permissions' => ['ssh', 'execute'],
        ],
    ],

    'security' => [
        'allowed_commands' => [
            'ls',
            'pwd',
            'cd',
            'cat',
            'head',
            'tail',
            'grep',
            'find',
            'ps',
            'top',
            'df',
            'du',
            'free',
            'who',
            'whoami',
            'date',
            'uptime',
            'uname',
            'history',
            'clear',
            'exit',
            'logout',
            'mkdir',
            'rmdir',
            'touch',
            'rm',
            'cp',
            'mv',
            'chmod',
            'chown',
            'wget',
            'curl',
            'ping',
            'traceroute',
            'netstat',
            'ss',
            'systemctl',
            'service',
            'journalctl',
            'crontab',
            'git',
            'docker',
            'npm',
            'composer',
            'php',
            'python',
            'node',
        ],

        'blocked_commands' => [
            'sudo',
            'su',
            'passwd',
            'useradd',
            'userdel',
            'usermod',
            'shutdown',
            'reboot',
            'halt',
            'init',
            'killall',
        ],

        'max_execution_time' => 300,
        'max_output_size' => 1024 * 1024, // 1MB
    ],

    'logging' => [
        'enabled' => true,
        'level' => 'info',
        'file' => storage_path('logs/whisp.log'),
    ],
];
